# Generated by Django 4.0.2 on 2022-04-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_section_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
