# Generated by Django 4.0.2 on 2022-04-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_section_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prereqString',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
